src/handlers/list-xero-tax-rates.handler.ts
src/index.ts
src/tools/list-tax-rates.tool.ts

Adds the ability to retrieve tax rates to support countries with more complex tax

Add list tax rates functionality

---

src/tools/list-contacts.tool.ts

Removed bank details, tax numbers, addresses, and phone numbers from the list contacts tool response

Update list contacts response formatting

---

README.md

Adds the list tax rates tool to the list of available tools in the readme file

Add list tax rates tool to readme

---

README.md
src/handlers/list-xero-quotes.handler.ts
src/index.ts
src/tools/list-quotes.tool.ts

Adds the ability to list quotes from Xero

Add Xero quotes listing functionality

---

README.md
src/handlers/create-xero-quote.handler.ts
src/index.ts
src/tools/create-quote.tool.ts

Enables the creation of quotes in Xero

Add Xero quote creation functionality

---

src/handlers/create-xero-invoice.handler.ts
src/tools/create-invoice.tool.ts

Enables multiple line items to be created when an invoice is created

Update invoice creation to support multiple line items

---

README.md
src/handlers/update-xero-contact.handler.ts
src/index.ts
src/tools/update-contact.tool.ts

Allows the LLM to update a contact

Implement contact update functionality

---

README.md
src/handlers/update-xero-invoice.handler.ts
src/index.ts
src/tools/update-invoice.tool.ts

Allows a draft invoice to be updated and returns an error if a non draft invoice is targeted to be updated

Implement invoice update functionality

---

src/handlers/list-xero-invoices.handler.ts
src/tools/list-invoices.tool.ts

Adds the ability to list invoices that match an invoice number or invoice numbers.  Also changes the sorting of invoices returned to Descending by Updated date rather than the default Ascending by Updated date and Id

Add invoice number filter and sort by updated date desc

---

README.md
src/handlers/list-xero-credit-notes.handler.ts
src/index.ts
src/tools/list-credit-notes.tool.ts

Adds the ability to list credit notes. Either all credit notes or the credit notes for a provided contact id.

Implement list credit note functionality

---

README.md
src/handlers/create-xero-credit-note.handler.ts
src/index.ts
src/tools/create-credit-note.tool.ts

Enables the ability to create credit notes

Implement create credit note functionality

---

src/handlers/create-xero-contact.handler.ts
src/handlers/create-xero-credit-note.handler.ts
src/handlers/create-xero-invoice.handler.ts
src/handlers/create-xero-quote.handler.ts
src/handlers/list-xero-accounts.handler.ts
src/handlers/list-xero-contacts.handler.ts
src/handlers/list-xero-credit-notes.handler.ts
src/handlers/list-xero-invoices.handler.ts
src/handlers/list-xero-quotes.handler.ts
src/handlers/list-xero-tax-rates.handler.ts
src/handlers/update-xero-contact.handler.ts
src/handlers/update-xero-invoice.handler.ts
src/helpers/get-package-version.ts

Switches the user agent from the xero-node SDK default to xero-mcp-server-{version-number}

Update the user agent string in the headers

---

examples/openai-agents/README.md
examples/openai-agents/main.py

Adds an example of how to use the OpenAI agents SDK with the Xero MCP server

Add OpenAI agents SDK example

---

README.md
src/handlers/list-xero-quotes.handler.ts
src/handlers/update-xero-quote.handler.ts
src/tools/list/list-quotes.tool.ts
src/tools/update/index.ts
src/tools/update/update-quote.tool.ts

Allows updating of draft quotes and adds the quote ID to the list quotes outputs to support proper updating

Add update quote functionality and update list quotes implementation

---

README.md
src/clients/xero-client.ts
src/handlers/list-xero-trial-balance.handler.ts
src/tools/list/index.ts
src/tools/list/list-trial-balance.tool.ts

Adds the ability to retrieve a trial balance

Add trial balance listing functionality

---

README.md
src/handlers/list-xero-items.handler.ts
src/tools/list/index.ts
src/tools/list/list-items.tool.ts

Adds the ability to retrieve a list of items

feat: Add list items functionality

---

README.md
src/handlers/update-xero-credit-note.handler.ts
src/tools/list/list-credit-notes.tool.ts
src/tools/update/index.ts
src/tools/update/update-credit-note.tool.ts

Allows updating of credit notes and outputs the Credit note ID and Number in list credit notes

feat: Add credit note update tool and improve list credit notes

---

src/consts/deeplinks.ts
src/handlers/create-xero-bank-transaction.handler.ts
src/handlers/update-xero-bank-transaction.handler.ts
src/tools/create/create-bank-transaction.tool.ts
src/tools/create/index.ts
src/tools/update/index.ts
src/tools/update/update-bank-transaction.tool.ts

Adds the ability to create and update bank transactions for an org.

Add tools to create and update bank transactions

---

README.md
src/handlers/list-xero-bank-transactions.handler.ts
src/helpers/format-line-item.ts
src/tools/list/index.ts
src/tools/list/list-bank-transactions.tool.ts
src/tools/list/list-invoices.tool.ts

Adds the ability to list all bank transactions for an org, or just the transactions for a specific bank account.

Add list bank transactions tool

---

src/clients/xero-client.ts
src/handlers/create-xero-item.handler.ts
src/handlers/update-xero-item.handler.ts
src/tools/create/create-item.tool.ts
src/tools/create/index.ts
src/tools/update/index.ts
src/tools/update/update-item.tool.ts

Adds tools to create items and update items.
I've deliberately left out changes to the README so I don't create a conflict with PR #49.
I'll make another PR with the readme change after #49 has been merged.

feat: add create item and update item functionality

---

README.md

Updated the README.md with additional links and instructions for use
Tip: You can compare how it looks in Markdown by using "Compare via Rich Diff" below:
https://github.com/XeroAPI/xero-mcp-server/pull/49/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

docs: update README.md with additional links and instructions for use

---

README.md
src/handlers/create-xero-bank-transaction.handler.ts
src/handlers/list-aged-payables-by-contact.handler.ts
src/handlers/list-aged-receivables-by-contact.handler.ts
src/helpers/format-aged-report-filter.ts
src/tools/list/index.ts
src/tools/list/list-aged-payables-by-contact.tool.ts
src/tools/list/list-aged-receivables-by-contact.tool.ts

Added tools for the aged receivables by contact and aged payables by contact reports.
Also, added a missing `await xeroClient.authenticate();` in the  create bank transactions tool.

Tools for Aged by Contact Reports

---

README.md
src/clients/xero-client.ts
src/handlers/list-xero-timesheets.handler.ts
src/tools/create/index.ts
src/tools/delete/index.ts
src/tools/get/index.ts
src/tools/list/index.ts
src/tools/tool-factory.ts
src/tools/update/index.ts

Added 8 endpoints relating to Timesheets in Payroll for micro-interactions
Added a single `get` endpoint and also a `delete` endpoint

feat: add payroll timesheet tools and handlers

---

README.md
src/handlers/list-xero-contact-groups.handler.ts
src/tools/list/index.ts
src/tools/list/list-contact-groups.tool.ts

Added Handler and Tool for list contact groups. This also handles the optional contact group id to get the contacts associated with a specific contact group.

List Contact Groups 

---

src/consts/deeplinks.ts
src/handlers/create-xero-invoice.handler.ts
src/handlers/update-xero-invoice.handler.ts
src/helpers/format-line-item.ts
src/helpers/get-deeplink.ts
src/tools/create/create-invoice.tool.ts
src/tools/update/update-invoice.tool.ts

This adds the ability to add items and tracking categories to invoices.  It also adds descriptions to invoice fields and enables users to create both accounts receivable and accounts payable invoices.

Add item and tracking support to invoices

---

src/handlers/list-xero-contacts.handler.ts
src/tools/list/list-contacts.tool.ts

Adds an optional paging parameter to the list-contacts tool to resolve #68

Add paging to contacts

---

src/handlers/create-xero-invoice.handler.ts
src/tools/create/create-invoice.tool.ts

Hello, I added the invoice date to create invoice. 
Would be great if this could be merged in the main trunk.
Cheers,

add invoice date to create xero invoice
